{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-taxa
  version: {{ version }}

source:
  path: ../..

build:
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - setuptools
    - pandas
    - qiime2 {{ release }}.*
    - q2templates {{ release }}.*
    - q2-types {{ release }}.*

test:
  imports:
    - q2_taxa
    - qiime2.plugins.taxa

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
